/**
 * rol: Generador de doc viva de Netrunner (Wave 6 — skill auto-generante).
 * Genera/actualiza README.generated.md y AGENTS.md desde el snapshot del proyecto
 * (rama, versiones, cobertura, servicios, pendientes). Es la feature de documentación:
 * "forzar la creación de documentación del proyecto, con el agente y automáticamente".
 *
 * SPEC (Mandamiento 0):
 *   Como un agente que opera un proyecto Netrunner,
 *   quiero que el motor genere la documentación desde el snapshot,
 *   para que la skill auto-generante documente todo al día.
 *
 * AC (features/generate.feature):
 *   AC-1 generateDocs(dir) → README.generated.md + AGENTS.md.
 *   AC-2 README incluye stack, git, versiones, cobertura, servicios, pendientes.
 *   AC-3 sin snapshot → genera con defaults (no falla).
 *   AC-4 idempotente (sobreescribe).
 */
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { buildSnapshot } from '../context/snapshot'

/** rol: genera el markdown del README desde el snapshot. */
function readmeContent(snap: Awaited<ReturnType<typeof buildSnapshot>>): string {
  const lines: string[] = [
    '# Project (generated by Netrunner)',
    '',
    '> Living documentation, auto-generated. Do not edit by hand.',
    '',
    '## Git state',
    `- Branch: ${snap.git.branch ?? 'no repo'}`,
    `- Remote: ${snap.git.remoteUrl ?? 'none'}`,
    '',
    '## Versions (prod)',
    ...Object.entries(snap.versions.prod).map(([k, v]) => `- ${k}: ${v}`),
    '',
    '## Test coverage',
    `- Lines: ${snap.coverage.lines}% · Functions: ${snap.coverage.functions}%`,
    '',
    '## Services',
    ...snap.services.services.map((s) => `- ${s.name}: ${s.url ?? 'no url'}`),
    '',
    '## Pending (TODO/FIXME)',
    ...snap.todos.todos.slice(0, 10).map((t) => `- [${t.tag}] ${t.file}:${t.line} — ${t.text}`),
    '',
  ]
  return lines.join('\n')
}

/** rol: genera AGENTS.md SOLO si no existe (no pisar AGENTS.md rico del usuario o de init — fix auditor de visión). */
function agentsContent(existing: string | null): string | null {
  if (existing) return null // respeta AGENTS.md existente (init escribe uno rico)
  return `# AGENTS.md (generado por Netrunner)

Este proyecto es operable por agentes de IA vía Netrunner. Conecta el server MCP (netrunner --mcp) y usa sus tools (explore/callers/callees/impact/rg/ops) para entender y operar el proyecto sin leer archivos masivamente.
`
}

/** rol: genera la documentación viva del proyecto (idempotente, AC-4). */
export async function generateDocs(projectDir: string): Promise<{ written: string[] }> {
  const snap = await buildSnapshot(projectDir)
  const readmePath = join(projectDir, 'README.generated.md')
  const agentsPath = join(projectDir, 'AGENTS.md')
  const existingAgents = existsSync(agentsPath) ? readFileSync(agentsPath, 'utf8') : null
  mkdirSync(dirname(readmePath), { recursive: true })
  writeFileSync(readmePath, readmeContent(snap))
  const written: string[] = ['README.generated.md']
  // solo escribe AGENTS.md si NO existe (no pisar uno rico — fix auditor de visión)
  const agents = agentsContent(existingAgents)
  if (agents) {
    writeFileSync(agentsPath, agents)
    written.push('AGENTS.md')
  }
  return { written }
}
